# Generated by Django 2.0.5 on 2021-10-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopzipcodes',
            name='tax',
        ),
        migrations.AddField(
            model_name='zipcodes',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
    ]
