# Generated by Django 2.0.5 on 2021-11-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0002_auto_20211009_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='seller_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
