# Generated by Django 2.0.5 on 2021-12-09 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0003_users_seller_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPaymentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('payment_type', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_request', models.TextField()),
                ('payment_response', models.TextField()),
                ('is_payment', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_api.ProductsOrder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_payment_information',
            },
        ),
    ]
