# Generated by Django 2.0.5 on 2022-08-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0004_productpaymentinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrderDeliveryFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.FloatField(default=0)),
                ('amount_max', models.FloatField(default=0)),
                ('amount_min', models.FloatField(default=0)),
                ('amount_type', models.CharField(choices=[('FIX_AMOUNT', ('FIX_AMOUNT', 'Fix Amount')), ('PERCENTAGE', ('PERCENTAGE', 'Percentage'))], default='FIX_AMOUNT', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_order_delivery_fee',
            },
        ),
    ]
