# Generated by Django 2.0.5 on 2022-08-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0005_productorderdeliveryfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsorder',
            name='delivery_method',
            field=models.TextField(default='delivery', max_length=100, null=True),
        ),
    ]
