# Generated by Django 2.0.5 on 2022-08-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0006_productsorder_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsorder',
            name='phone_number',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
