# Generated by Django 2.0.5 on 2022-09-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0009_shoppickupstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsorder',
            name='picup_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='productsorder',
            name='picup_location',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
